name: "Build image"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-image:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4

        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: echo ${{ secrets.DOCKER_PAT }} | docker login -u rmpablo1 --password-stdin
      - run: docker build -t rmpablo1/application
